In [2]:
import numpy as np

In [5]:
x = np.array([3,5,1,6,2,7])
## It returns the sorted positions in an array
print(np.argsort(x))
## we can use that array of position in our data array
print(x[np.argsort(x)])

[2 4 0 1 3 5]
[1 2 3 5 6 7]


In [7]:
grades = np.array([3,5,1,6,2,7])
ages = np.array([8,10,6,11,7,12])
sort_idx = np.argsort(ages)
## Sorting related data using the indexes of other array
print(grades[sort_idx])
print(ages[sort_idx])

[1 2 3 5 6 7]
[ 6  7  8 10 11 12]


In [8]:
## Converting to a python list (commas are shown as separators)
print(list(grades[sort_idx]))

[1, 2, 3, 5, 6, 7]


In [12]:
## Show in reverse order
print(ages[sort_idx][::-1])


[12 11 10  8  7  6]
