In [1]:
import numpy as np
np.__version__

'1.18.5'

In [4]:
x = np.arange(75, 201)
print(x)
type(x)

[ 75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92
  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110
 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128
 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146
 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164
 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182
 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200]


numpy.ndarray

In [4]:
y = np.arange(1000000)
y = y ** 2

In [6]:
## With simple python that operation would be much slower
z = list(range(1000000))
## This broadcast operation is not supported in normal python
z = z ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [7]:
## Data must be of the same type, numpy will try to coerce data
animal = ['dog', 'Mammal', 45, 7]
print(animal)

['dog', 'Mammal', 45, 7]


In [8]:
## In this case everything is change to strings
np.array(animal)

array(['dog', 'Mammal', '45', '7'], dtype='<U6')

In [10]:
ndim = np.arange(27)
# 3 dimensional array
ndim_reshaped = ndim.reshape(3 ,3 ,3)
print (ndim_reshaped)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [19]:
# Matrix of ones 3 rows 5 columns
print(np.ones((3, 5)), end='\n\n')
print(np.zeros((3, 5)), end='\n\n')
#Identity Matrix, does not get a tuple
print(np.eye(5, 5), end='\n\n')

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]



In [22]:
## 15 random ints from 0 to 9
data = np.random.randint(10, size=15)
print(data)

[7 5 6 2 5 3 7 7 4 1 1 5 9 9 0]


In [27]:
# Slicing 1d array is easy
print(data[0])
print(data[:3])
print(data[4:9])

7
[7 5 6]
[5 3 7 7 4]


In [34]:
data = data.reshape(3, 5)
print(data)
## Print the first row
print(data[0])
## Print the first column
print(data[:, 0])
print(data[1, 1])


[[7 5 6 2 5]
 [3 7 7 4 1]
 [1 5 9 9 0]]
[7 5 6 2 5]
[7 3 1]
7
